require("options")
require("keymaps")
require("plugins.plugins-setup")

require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/toggleterm")
require("plugins/navigator")
require("plugins/autopairs")
